### ISSUE TITLE
Python install issue when using 3.9

### ISSUE THREAD

**Issue by tcal-x** [lnis-uofu/yosys_prefix_trees#10]
I see this on my gLinux machine, which has Python 3.9.9 installed:

```
yosys> opt_pptrees 
1. Executing opt_pptrees pass.
Running python script from shell: python3 -c "import sys; from pptrees.yosys_alu import yosys_alu as tree; g=tree(1); g.yosys_map('/tmp/yosys-python-4SvEOM','behavioral');"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/google/home/tcal/.local/lib/python3.9/site-packages/pptrees/yosys_alu.py", line 31, in yosys_map
    with importlib.resources.path("pptrees","mappings") as pkg_map_dir:
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/usr/local/google/home/tcal/.local/lib/python3.9/site-packages/pptrees/mappings'
ERROR: Synth_opt_adder: execution of command "import sys; from pptrees.yosys_alu import yosys_alu as tree; g=tree(1); g.yosys_map('/tmp/yosys-python-4SvEOM','behavioral');" failed: return code 1.
```

**Comment by tdene** [comment]
Thanks a lot for trying it out!

Interesting. 
I've been testing on Python 3.6.

It seems the issue is that Python 3.9's importlib no longer likes to refer to directories, as opposed to source files.

I will patch this upstream and make a note to test on Python 3.9 in the future.

**Comment by tdene** [comment]
Confirmed, this is a Python 3.8 -> 3.9 fix as can be seen [here](https://bugs.python.org/issue44162).

**Comment by tdene** [comment]
Should have been fixed by [this PR](https://github.com/tdene/synth_opt_adders/pull/35).

**Comment by tcal-x** [comment]
I seem to get a different error now:
```
2. Executing opt_pptrees pass.
Running python script from shell: python3 -c "import sys; from pptrees.yosys_alu import yosys_alu as tree; g=tree(1); g.yosys_map('/tmp/yosys-python-Es8hn2','behavioral');"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/google/home/tcal/.local/lib/python3.9/site-packages/pptrees/yosys_alu.py", line 32, in yosys_map
    with importlib.resources.path("pptrees.mappings",map_file) as pkg_map_file:
  File "/usr/lib/python3.9/importlib/resources.py", line 165, in path
    _common.as_file(files(package).joinpath(_normalize_path(resource)))
  File "/usr/lib/python3.9/importlib/resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "/usr/lib/python3.9/importlib/_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "/usr/lib/python3.9/importlib/_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "/usr/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
ERROR: Synth_opt_adder: execution of command "import sys; from pptrees.yosys_alu import yosys_alu as tree; g=tree(1); g.yosys_map('/tmp/yosys-python-Es8hn2','behavioral');" failed: return code 1.
```
After this, there is a `/tmp/yosys-python-Es8hn2/`, but it is empty.

**Comment by tdene** [comment]
Unexpected.

Let me install Python 3.9 and use that as my dev environment. I will ping you when it also works on 3.9.

**Comment by tcal-x** [comment]
I am no longer seeing these issues after updating.
